### ISSUE TITLE
[DEV] Make configuration flexible to different deployments

### ISSUE THREAD

**Issue by synackd** [OpenCHAMI/ochami#6]
## Short Description

The configuration currently is geared toward querying services under a single base URI, e.g. when running an API gateway. As mentioned in #4, `ochami` should support the ability to communicate with services deployed using a variety of deployment methods. In other words, `ochami` should support using different base URIs or path URIs for each service.

See these comments:

- https://github.com/OpenCHAMI/ochami/pull/4#issuecomment-2686572453
- https://github.com/OpenCHAMI/ochami/pull/4#issuecomment-2688512250

## Long Description

The current cluster configuration mechanism looks like this:

```yaml
clusters:
  - name: foobar
    cluster:
      base-uri: https://foobar.openchami.cluster:8443
```

Service base paths (e.g. `/hsm/v2`) are hard-coded and appended to `base-uri`. This pigeonholes deployment options into a specific case if one desires to use `ochami`. A more flexible configuration posed might look like this:

```yaml
clusters:
  - name: foobar
    cluster:
      # URI of API gateway, if used . Per-service `<service>-uri` options either override this option
      # (if the value is a full URI, e.g. 'https://...') or are appended to this option (if the value is a relative
      # path, e.g. '/hsm/v2'). This allows one to not have to repeat URIs, but allows the flexibility to
      # customize both service base paths and entire service URIs.
      api-uri: https://foobar.openchami.cluster:8443

      # Override default SMD base path of `/hsm/v2`. This uses a relative path, so it gets appended to
      # 'api-uri', so SMD requests will get directed to:
      #
      # https://foobar.openchami.cluster:8443/smd
      #
      smd-uri: '/smd'
      #
      # Alternatively, override the entire SMD service URI. This uses a full URI, so it overrides `api-uri`.
      # So, SMD requests will get directed to:
      #
      # https://my.cool.cluster/hsm/v2
      #
      smd-uri: 'https://my.cool.cluster/hsm/v2'
      #
      # No other overrides specified, so default values used. E.g. BSS requests
      # would go to https://foobar.openchami.cluster:8443/boot/v1
```

The above allows one to optionally use `api-uri`, formerly `base-uri`, as a base URI for OpenCHAMI services, e.g. if most services were hosted under it. Various `<service>-uri` options can be used to either change the service base path from the default (e.g. something different than `hsm/v2` for SMD) or override the `api-uri` altogether and use an entirely different URI for a service.

For example, going entirely the opposite direction from using `api-uri`, if all of the OpenCHAMI services were running bare metal on different ports under the same interface, the config might look like:

```yaml
clusters:
  - name: foobar
    cluster:
      smd-uri: https://localhost:27779/hsm/v2
      bss-uri: https://localhost:27778/boot/v1
      cloud-init-uri: https://localhost:27777/cloud-init
      pcs-uri: https://localhost:28007
```

This mechanism expands the deployment options that `ochami` supports:

- Various API gateway configurations (stock or custom, docker compose or Kubernetes and (ideally) beyond)
- Bare metal (e.g. for testing services)
